config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'lists#index'

  resources :lists, only: %i[index show new create destroy] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }

  validates :movie_id, presence: true, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])

    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to list_path, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.photo.attached?
        if @list.save
          format.html { redirect_to list_path(@list), notice: 'List was successfully created.' }
          format.json { render :show, status: :created, location: @list }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show; end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New movie</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :movie %>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.submit "Add movie", :class => "btn btn-outline-secondary"%>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to list", list_path(@list) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<div class="container" d-flex>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">IMDbest</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Watchlists</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/lists/new">New watchlist</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
</div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="text-center">Watchlists</h1>


  <div class="d-flex align-items-start flex-column align-items-center m-5" style="height: 500px;">
    <% @lists.each do |list| %>
      <div class="card-category d-flex align-self-stretch m-1" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, crop: :fill %>')">
        <%= link_to list.name.capitalize, list, :class => "d-flex justify-content-center text-light" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New watchlist</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.submit "Create watchlist", :class => "btn btn-outline-secondary"%>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="d-flex align-items-start flex-column align-items-center m-5" style="height: 100px;">
    <div class="card-category d-flex align-self-stretch m-1 align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, crop: :fill %>')">
      <%= @list.name.capitalize %>
    </div>
  </div>
</div>

  <div class="cards d-flex justify-content-center">
    <div class="row col-sm-12 d-flex .align-content-start">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="card m-2" style="width: 25rem;">
          <img class="card-img-top mt-2" src="<%= bookmark.movie.poster_url %>" alt="">
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"> <strong> <%= bookmark.movie.title %> </strong> </h5>
              <p class="card-text">  <%= bookmark.movie.overview %></p>
              <p class="card-text"> <strong>Rating:</strong> <%= bookmark.movie.rating %></p>
              <p class="card-text"> <strong>Comment:</strong> <%= bookmark.comment %></p>
              <%= link_to "Delete this movie", bookmark_path(bookmark), :class => "btn btn-outline-danger btn-sm d-flex justify-content-center mt-auto", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this movie?" } %>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container d-flex justify-content-around mb-5 mt-3">

  <%= link_to "Add a movie to this watchlist", new_list_bookmark_path(@list), :class => "btn btn-outline-secondary" %>
  <%= link_to "Delete this watchlist", list_path(@list), :class => "btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
</div>